DROP TABLE RESERVATION
CASCADE CONSTRAINT;

DROP SEQUENCE SEQ_RES;

CREATE TABLE RESERVATION (
SEQ_RES NUMBER(8) CONSTRAINT PK_RES PRIMARY KEY,
SEQ_PEN NUMBER(8) NOT NULL,
SEQ_ROOM NUMBER(8) NOT NULL,
ID VARCHAR2(20) NOT NULL,
CHECKIN DATE NOT NULL,
CHECKOUT DATE NOT NULL,
PERSON_TOTAL NUMBER(8) NOT NULL,
BBQ NUMBER(8) NOT NULL,
PRICE_RES NUMBER(8) NOT NULL,
DATE_RES DATE NOT NULL,
DEL_RES NUMBER(1) NOT NULL,
CONSTRAINT FK_RES_PEN FOREIGN KEY (SEQ_PEN) REFERENCES PENSION(SEQ_PEN),
CONSTRAINT FK_RES_ROOM FOREIGN KEY (SEQ_ROOM) REFERENCES ROOM(SEQ_ROOM),
CONSTRAINT FK_RES_ID FOREIGN KEY (ID) REFERENCES MEMBER(ID) 
);

CREATE SEQUENCE SEQ_RES
INCREMENT BY 1
<<<<<<< HEAD
START WITH 1;

-- 특정 날짜 ?에 따른 예약정보 가져오기
SELECT SEQ_RES, SEQ_PEN, SEQ_ROOM, ID, CHECKIN, CHECKOUT, PERSON_TOTAL, BBQ, PRICE_RES, DATE_RES, DEL_RES
FROM RESERVATION
WHERE (CHECKIN = NULL AND CHECKOUT = NULL) OR 
(CHECKIN < TO_DATE((?), 'YYYY/DD/MM') AND CHECKOUT > TO_DATE((?), 'YYYY/DD/MM'));

SELECT SEQ_ROOM, NAME_ROOM, TYPE_ROOM, SIZE_ROOM, PERSON_MIN, PERSON_MAX, PRICE_BASIC, PRICE_WEEKEND, 
PRICE_SEASON_BASIC, PRICE_SEASON_WEEKEND, INFO_ROOM, ITEM, SEQ_PEN, DEL_ROOM 
FROM ROOM
WHERE SEQ_PEN=4
INTERSECT 
(SELECT SEQ_RES, SEQ_PEN, SEQ_ROOM, ID, CHECKIN, CHECKOUT, PERSON_TOTAL, BBQ, PRICE_RES, DATE_RES, DEL_RES
FROM RESERVATION
WHERE (CHECKIN = NULL AND CHECKOUT = NULL) OR (CHECKIN < TO_DATE((2017/08/23), 'YYYY/DD/MM') AND CHECKOUT > TO_DATE((2017/08/23), 'YYYY/DD/MM')));

