DROP TABLE RESERVATION
CASCADE CONSTRAINT;

DROP SEQUENCE SEQ_RES;

CREATE TABLE RESERVATION (
SEQ_RES NUMBER(8) CONSTRAINT PK_RES PRIMARY KEY,
SEQ_PEN NUMBER(8) NOT NULL,
SEQ_ROOM NUMBER(8) NOT NULL,
ID VARCHAR2(20) NOT NULL,
CHECKIN DATE NOT NULL,
CHECKOUT DATE NOT NULL,
PERSON_TOTAL NUMBER(8) NOT NULL,
BBQ NUMBER(8) NOT NULL,
PRICE_RES NUMBER(8) NOT NULL,
DATE_RES DATE NOT NULL,
DEL_RES NUMBER(1) NOT NULL,
CONSTRAINT FK_RES_PEN FOREIGN KEY (SEQ_PEN) REFERENCES PENSION(SEQ_PEN),
CONSTRAINT FK_RES_ROOM FOREIGN KEY (SEQ_ROOM) REFERENCES ROOM(SEQ_ROOM),
CONSTRAINT FK_RES_ID FOREIGN KEY (ID) REFERENCES MEMBER(ID) 
);

CREATE SEQUENCE SEQ_RES
INCREMENT BY 1
START WITH 1;